name: unige_app_flutter
description: Marketing Data Collection App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pinput: ^5.0.0
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.0.13
  http: ^1.2.2
  syncfusion_flutter_datepicker: ^27.2.4
  toggle_switch: ^2.0.1
  syncfusion_flutter_sliders: ^27.2.4
  flutter_sound: ^9.2.13
  permission_handler: ^12.0.0+1
  google_fonts: ^6.2.1
  path_provider: ^2.0.11
  flutter_camera: ^1.0.0
  record: ^4.4.3
  audioplayers: ^6.1.0
  video_player: ^2.4.10
  file_picker: ^8.1.4
  googleapis: any
  googleapis_auth: any
  url_launcher: ^6.3.1
  month_picker_dialog: ^2.0.2
  intl: ^0.18.1
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/audio/
    - assets/flags/
