// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj7YJZax3_TIZqytOWkGJ5tiNBW4VC_mI',
    appId: '1:751987554712:web:6405757285b81499c353ed',
    messagingSenderId: '751987554712',
    projectId: 'unige-c5714',
    authDomain: 'unige-c5714.firebaseapp.com',
    storageBucket: 'unige-c5714.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGV-AqCq-FaH38hndkYcxBSBbC3qBWyHM',
    appId: '1:751987554712:android:805d52596fcb2b92c353ed',
    messagingSenderId: '751987554712',
    projectId: 'unige-c5714',
    storageBucket: 'unige-c5714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR8HfvQr-cyHzc0SEAstFy9_pYXHPE8DI',
    appId: '1:751987554712:ios:d1921e2d2afafa39c353ed',
    messagingSenderId: '751987554712',
    projectId: 'unige-c5714',
    storageBucket: 'unige-c5714.appspot.com',
    androidClientId:
        '751987554712-n90ekmmbsd1dmast276m46q5bklnvgib.apps.googleusercontent.com',
    iosClientId:
        '751987554712-057bq4qhtgm913fq3qvb91snrgacqs4l.apps.googleusercontent.com',
    iosBundleId: 'com.pts.unigeApp',
  );
}
