// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMCFZN63tozhNOGSilgisgSC_6IkfSbtQ',
    appId: '1:688815766660:web:f181f699b0da57228496d1',
    messagingSenderId: '688815766660',
    projectId: 'unige-app',
    authDomain: 'unige-app.firebaseapp.com',
    storageBucket: 'unige-app.firebasestorage.app',
    measurementId: 'G-1XND085KK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCYHsnxvcbhfvChuHH9bHaFIPjIxT0yTI',
    appId: '1:688815766660:android:c5a498d36a030caa8496d1',
    messagingSenderId: '688815766660',
    projectId: 'unige-app',
    storageBucket: 'unige-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWRtfBBUvDGMkepFMqP7VV_MXLA1auMBk',
    appId: '1:688815766660:ios:94fcf470465668048496d1',
    messagingSenderId: '688815766660',
    projectId: 'unige-app',
    storageBucket: 'unige-app.firebasestorage.app',
    iosBundleId: 'com.kpts.unige',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWRtfBBUvDGMkepFMqP7VV_MXLA1auMBk',
    appId: '1:688815766660:ios:51d3e927b56c4db98496d1',
    messagingSenderId: '688815766660',
    projectId: 'unige-app',
    storageBucket: 'unige-app.firebasestorage.app',
    iosBundleId: 'com.kpts.unigeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMCFZN63tozhNOGSilgisgSC_6IkfSbtQ',
    appId: '1:688815766660:web:55ccca5946f804678496d1',
    messagingSenderId: '688815766660',
    projectId: 'unige-app',
    authDomain: 'unige-app.firebaseapp.com',
    storageBucket: 'unige-app.firebasestorage.app',
    measurementId: 'G-BCVG0CWZXT',
  );
}
